### ISSUE TITLE
Missing support for jsonb columns

### ISSUE THREAD

**Issue by SebastianVomMeer** [Lichtbit/generated_schema_validations#1]
GeneratedSchemaValidations cannot handle jsonb columns in Postgres. The migration succeeds but shows an error message at the end:

> NoMethodError: undefined method `jsonb' for #<GeneratedSchemaValidations::Table:0x00007f2b099fc1b8 @table_name="ahoy_events", @column_names=["visit_id", "user_id", "name"], @possible_belongs_to_not_null_columns=[], @unique_indexes=[], @validations=[]>
> Did you mean?  json
> 
> Tasks: TOP => db:schema:dump
> (See full trace by running task with --trace)

**Comment by georf** [comment]
fixed by b673373bfd654d33e4f164fc3126bda0a97ceb21

new version: 0.2.3
